[package]
name = "worktree_setup_operations"
description = "File operations for worktree-setup"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
glob = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
worktree_setup_config = { workspace = true }
worktree_setup_copy = { workspace = true }
worktree_setup_git = { workspace = true }

[features]
default = []
fail-on-warnings = []

[dev-dependencies]
tempfile = { workspace = true }
